name: Update Formula

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'  # 每月 1 日和 15 日自动运行

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo (homebrew tap)
        uses: actions/checkout@v4

      - name: Fetch latest release info from sing-box-premium
        id: release
        run: |
          LATEST=$(curl -s https://api.github.com/repos/sb-community/sing-box-premium/releases/latest)
          VERSION=$(echo "$LATEST" | jq -r .tag_name)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download and calculate SHA256
        id: sha
        run: |
          BASE_URL="https://github.com/sb-community/sing-box-premium/releases/download/${VERSION}"

          # 定义平台和文件名
          declare -A files=(
            [darwin_arm]="sing-box-release-darwin-arm64.tar.gz"
            [darwin_amd64]="sing-box-release-darwin-amd64.tar.gz"
            [linux_amd64]="sing-box-release-linux-amd64.tar.gz"
            [linux_armv8]="sing-box-release-linux-armv8.tar.gz"
            [linux_armv7]="sing-box-release-linux-armv7.tar.gz"
          )

          # 下载并计算 hash
          for key in "${!files[@]}"; do
            url="${BASE_URL}/${files[$key]}"
            curl -L -o "$key.tar.gz" "$url"
            sha=$(sha256sum "$key.tar.gz" | awk '{print $1}')
            echo "${key}_url=${url}" >> $GITHUB_ENV
            echo "${key}_sha=${sha}" >> $GITHUB_ENV
          done

      - name: Generate Formula
        run: |
          TEMPLATE=brew.rb
          OUTPUT=Formula/sing-box-premium.rb

          mkdir -p Formula

          sed -e "s|{{version}}|$VERSION|g" \
              -e "s|{{darwin_arm_url}}|\"$darwin_arm_url\"|g" \
              -e "s|{{darwin_arm_sha256}}|$darwin_arm_sha|g" \
              -e "s|{{darwin_amd64_url}}|\"$darwin_amd64_url\"|g" \
              -e "s|{{darwin_amd64_sha256}}|$darwin_amd64_sha|g" \
              -e "s|{{linux_amd64_url}}|\"$linux_amd64_url\"|g" \
              -e "s|{{linux_amd64_sha256}}|$linux_amd64_sha|g" \
              -e "s|{{linux_armv8_url}}|\"$linux_armv8_url\"|g" \
              -e "s|{{linux_armv8_sha256}}|$linux_armv8_sha|g" \
              -e "s|{{linux_armv7_url}}|\"$linux_armv7_url\"|g" \
              -e "s|{{linux_armv7_sha256}}|$linux_armv7_sha|g" \
              "$TEMPLATE" > "$OUTPUT"

      - name: Commit and Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add Formula/sing-box-premium.rb
          git commit -m "Update formula to version $VERSION" || echo "No changes"
          git push
